### ISSUE TITLE
WorkSpace client startup with a account name pass as an argument 

### ISSUE THREAD

**Issue by amir-khatibzadeh** [awsdocs/amazon-workspaces-user-guide#7]
Hey,

I tried to find the correct place to send a feature request on the AWS WorkSpace client, but I could not find one.
So here I am, and I am sorry if it is not directly related to the WorkSpace docs.

Would it be possible to pass the WorkSpace profile as an argument to the windows client executable so I can open a specific profile among all the saved profiles I have by sending the profile name or something like that?

Thank you

**Comment by amir-khatibzadeh** [comment]
Meanwhile, I am using the following PowerShell script to do what I want to do:

```
[CmdletBinding()]
param (
    [string]
    $ProfileName
)
$currentPWD = $PWD
Set-Location -Path "$env:USERPROFILE\appdata\Local\Amazon Web Services\Amazon WorkSpaces\"
$registrationList = Get-Content -Path .\RegistrationList.json -Raw | ConvertFrom-Json -Depth 10
$userSettings = Get-Content -Path .\UserSettings.json -Raw | ConvertFrom-Json -Depth 10

$currentProfile = $registrationList | Where-Object CustomDescription -EQ $ProfileName
$measure = $currentProfile | Measure-Object
if($measure.Count -gt 0){
    $userSettings.CurrentRegistration = $currentProfile[0]
    $content = $userSettings | ConvertTo-Json -Depth 10
    Set-Content -Path .\UserSettings.json -Value $content -Force
}

Start-Process -FilePath "C:\Program Files\Amazon Web Services, Inc\Amazon WorkSpaces\workspaces.exe"
Set-Location $currentPWD
```

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
